version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    depends_on:
      - redis
    ports:
      - "8080:8080"  # Host:Container port mapping
    image: navneetshukla/goredis
